# General
spring:
  application:
    name: igrp-cloud-gateway
  profiles:
    active: production

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    root: ${GATEWAY_LOG_LEVEL:DEBUG}
    cv.igrp.platform: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:DEBUG}
    reactor.netty.http.server: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: ${GATEWAY_LOG_LEVEL:DEBUG}