# Kubernetes configuration
spring:
  cloud:
    discovery:
      enabled: true
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        service-labels:
          gateway.expose: "true"