# General
spring:
  application:
    name: igrp-cloud-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    gateway:
      access: unrestricted

# Logging configuration
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    cv.igrp.platform: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.discovery.DiscoveryClientRouteDefinitionLocator: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway.handler.predicate: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.loadbalancer: ${GATEWAY_LOG_LEVEL:DEBUG}
    org.springframework.cloud.kubernetes.discovery: ${GATEWAY_LOG_LEVEL:DEBUG}
