# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    disable-delta: false
    refresh:
      enable: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Kubernetes configuration
spring:
  cloud:
    discovery:
      enabled: true
    kubernetes:
      discovery:
        enabled: false