# Eureka client configuration (disabled in production, using Kubernetes instead)
eureka:
  client:
    enabled: false

# Kubernetes configuration
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
              include-expression: "metadata['gateway.expose'] == 'true'"
              route-id-prefix: "kubernetes_"
              url-expression: "'lb://'+serviceId"
              predicates:
                - name: Path
                  args:
                    pattern: "'/' + serviceId + '/**'"
                - name: Method
                  args:
                    methods: "['GET','POST','PUT','DELETE']"
              filters:
                - name: RewritePath
                  args:
                    regexp: "'/' + serviceId + '/(?<remaining>.*)'"
                    replacement: "'/${remaining}'"
    discovery:
      enabled: true
    kubernetes:
      discovery:
        enabled: true
        metadata:
          add-labels: true
          add-annotations: true
        all-namespaces: false
        service-labels:
          gateway.expose: "true"
      reload:
        enabled: true
        mode: event
        strategy: refresh
