spring.application.name=igrp-cloud-gateway
# Default profile to use when not specified
spring.profiles.default=${SPRING_ACTIVE_PROFILE:8080}
# Server configuration
server.port=${GATEWAY_PORT:8080}
# Gateway configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized