# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Kubernetes configuration
spring.cloud.kubernetes.config.enable-api=false
spring.cloud.kubernetes.config.enabled=false
spring.cloud.kubernetes.discovery.enabled=false
spring.cloud.kubernetes.loadbalancer.enabled=false
# Logging configuration
logging.level.root=INFO
logging.level.cv.igrp.platform=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG